{% set version = "0.2.4" %}

package:
  name: pyodide-cli
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/pyodide-cli/pyodide_cli-{{ version }}.tar.gz
  sha256: 8cebc6831bfd234b6413d9a73178b93800bd1f6dfa1567514cbfda5768f5095b

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  entry_points:
    - pyodide = pyodide_cli.__main__:main

requirements:
  host:
    - hatch-vcs
    - hatchling
    - pip
    - python >=3.10
  run:
    - python >=3.10
    - rich
    - typer >=0.6.0

test:
  imports:
    - pyodide_cli
  commands:
    - pip check
    - pyodide --version
    - pyodide --help
  requires:
    - pip

about:
  home: https://github.com/pyodide/pyodide-cli
  summary: The command line interface for the Pyodide project
  license: MPL-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - bollwyvl
