{% set python_min = "3.10" %}
{% set version = "0.3.0" %}

package:
  name: pyodide-cli
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/p/pyodide-cli/pyodide_cli-{{ version }}.tar.gz
  sha256: 247a7408f358326dd586477b5fe6eeb146edbed5f058923d258730e743457dd0

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  entry_points:
    - pyodide = pyodide_cli.__main__:main

requirements:
  host:
    - hatch-vcs
    - hatchling
    - pip
    - python {{ python_min }}
  run:
    - python >={{ python_min }}
    - rich
    - typer >=0.6.0

test:
  imports:
    - pyodide_cli
  commands:
    - pip check
    - pyodide --version
    - pyodide --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/pyodide/pyodide-cli
  summary: The command line interface for the Pyodide project
  license: MPL-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - bollwyvl
