# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  version: "0.4.2"
  python_min: "3.12"
  python_check_max: "3.14"

package:
  name: pyodide-cli
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/p/pyodide-cli/pyodide_cli-${{ version }}.tar.gz
  sha256: 8e6421f17b570fa5402254bc8bed6d032ac06ab5e1e83087ed8517d87bc86abc

build:
  number: 0
  noarch: python
  script:
    - ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation --disable-pip-version-check
  python:
    entry_points:
      - pyodide = pyodide_cli.__main__:main

requirements:
  host:
    - hatch-vcs
    - hatchling
    - pip
    - python ${{ python_min }}.*
  run:
    - python >=${{ python_min }}
    - rich
    - typer >=0.6.0

tests:
  - python:
      imports: pyodide_cli
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - ${{ python_check_max }}.*
  - requirements:
      run:
        - python ${{ python_min }}.*
    script:
      - pyodide --help
      - pyodide --version
      - python -c "v = __import__('pyodide_cli').__version__; print(v); assert v == '${{ version }}'"

about:
  summary: The command line interface for the Pyodide project
  license: MPL-2.0
  license_file: LICENSE
  homepage: https://pypi.org/project/pyodide-cli
  repository: https://github.com/pyodide/pyodide-cli
  documentation: https://pyodide.org

extra:
  recipe-maintainers:
    - bollwyvl
